### ISSUE TITLE
cant run app in development.

### ISSUE THREAD

**Issue by aravindle** [callstack/super-app-example#2]
## Ask your Question
I'm trying to run the app and it throws the error:-
"Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release." right after app starts. Anyway i can fix this. spent a day already on this library

**Comment by aravindle** [comment]
no i've checked out to individual commits in the finished branch and was able to run the apps individually when i was checked out to the commit b7a202f(b7a202f2fbdfdb06a5764f7ab7445eb9030146b4) but after checking out to 35af991 35af991256c9afa5f423d48198015d51296703ff ... the app fails to run..the exact procedure i am following is
1. yarn 
2. yarn bootstrap
3. yarn start:host-app --port 8081
4. split terminal
5. yarn start:mini-app --port 8082
6. new terminal
7. yarn run:host-app:android --port 8081

** I had to specify ports explicitly as earlier it was throwing port already in use error.  i havent checked out to release branch yet.

**Comment by jbroma** [comment]
Please do the following in order to get this working:

1. In `packages/host-app/index.js` please change the port for MiniApp to `8082`.
2. To resolve the issue from the original issue, inside emulator please enter the developer menu (on Mac it's `CMD + M`) then go to change bundle location and enter `localhost:8081`. This helped me to get the emulator to connect to development server for host-app
3. Finally, run `adb reverse tcp:8082 tcp:8082` to expose port for the mini-app server.

Let me know whether this helped!

**Comment by aravindle** [comment]
@jbroma No, it shows the same error: sharing the screenshots plus the code in index.js. I changed the bundle location to both localhost and my ipv4 address since i was running the app on physical device. Anything else i can try changing? please let me know.

![screen2](https://github.com/callstack/super-app-example/assets/139848214/6b640c77-ef59-4860-add5-2f1b5825bf9a)
![screen1](https://github.com/callstack/super-app-example/assets/139848214/25be026b-e4f7-4e5d-bbb5-3cae77e055f5)

**Comment by jbroma** [comment]
Your setup depends a lot on networking within your own network, and the problem lies entirely within the networking domain as I checked yesterday and managed to get it running on Android Emulator. 

I would start by checking whether the development server is even accessible within the browser on your physical device.

**Comment by aravindle** [comment]
sure, checking it.

**Comment by aravindle** [comment]
@jbroma 
Hi, i cross checked, the development server is accessible from my windows machine's browser but not from the mobile.
![screen3](https://github.com/callstack/super-app-example/assets/139848214/66f64704-b127-4afa-af76-c0b1e2f3560c)
![screen4](https://github.com/callstack/super-app-example/assets/139848214/d826f6f5-66da-4547-a9bd-8f2ec31f42c3)

Also, i cross checked if a the boilerplate react native template app is accessible through my mobile browser and it was accessible.
![screen5](https://github.com/callstack/super-app-example/assets/139848214/259b0284-7bda-476f-8231-2a74e1ddfdd5)

So, i guess i'll figure this out by myself but any inputs from repack perspective are appreciated. thankyou.
